# Generated by Django 3.2.7 on 2021-10-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='permission_code',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
