# Generated by Django 3.2.7 on 2021-10-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_permission_permission_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor_visit_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
