# Generated by Django 3.2.7 on 2021-10-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userappointment_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappointment',
            name='paid_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
