# Generated by Django 3.2.7 on 2021-10-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginattempt',
            name='ip',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
