# Generated by Django 3.2.7 on 2021-10-02 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_us_picture',
        ),
    ]
