# Generated by Django 3.2.7 on 2021-10-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicpicture',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
